/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
static yyconst short int yy_accept[294] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   18,   16,   17,   16,   16,   16,
       16,   16,   16,   16,   16,    5,   16,   16,    0,    0,
        0,   14,   14,   14,    0,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   14,
        0,    0,   10,    0,    0,    1,    0,    0,    0,    0,
        0,    0,    0,   15,   15,   15,    0,    0,    0,    0,
        0,    0,    9,    0,    0,    0,    4,    4,    4,    0,
        0,   14,   14,    0,    0,   10,    2,    0,    0,    0,

        0,   15,    0,    0,    0,   13,   13,   13,    0,    0,
        0,    0,    0,   12,   12,   12,    0,    0,    0,    4,
        0,    0,    0,   14,    0,    0,   15,   15,    0,    0,
        0,    0,   13,    0,    0,    0,    0,    0,   12,    4,
        4,    0,    0,    0,    0,   14,    0,    0,    0,   11,
       11,   11,    0,   15,   13,   13,    0,   12,   12,    0,
        0,    4,    0,    3,    3,    3,    3,    3,    3,    3,
        0,    0,    0,    0,    0,    0,    0,   11,    0,   15,
        0,   13,    0,   12,    0,    4,    0,    0,    3,    0,
        3,    3,    3,    0,    0,    0,   11,   11,    0,    0,

       13,    0,   12,    0,    3,    0,    0,    3,    3,    3,
        0,    3,    3,    0,    0,    0,    0,   11,    3,    0,
        0,    0,    0,    3,    3,    3,    0,    0,    0,    8,
        0,   11,    0,    0,    3,    3,    3,    3,    3,    0,
        3,    0,    0,    0,    0,    0,    3,    0,    3,    3,
        0,    0,    3,    3,    0,    0,    3,    3,    0,    6,
        0,    0,    3,    3,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
        1,    1,    1,    1,    1,    1,   26,   24,   27,   28,

       29,   30,   31,   24,   32,   24,   24,   33,   34,   35,
       36,   24,   37,   38,   39,   40,   41,   42,   24,   24,
       24,   24,   43,   44,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    5,    5,    6,
        7,    5,    8,    9,    8,    1,    5,   10,   10,    1,
        1,   11,    1,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,    1,    5
    } ;

static yyconst short int yy_base[335] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  734,  986,  986,   41,    0,  701,
       33,   43,   36,   59,   54,  986,  100,  141,   51,    0,
       31,   66,   70,    0,  725,  693,    0,    0,    0,  713,
        0,  182,   87,  714,   62,  677,   77,  106,  223,  707,
      704,    0,   61,  120,   94,   75,  697,  118,   81,    0,
      124,  675,    0,  688,  682,    0,  661,   87,  102,  668,
      674,    0,  128,  141,  146,    0,  174,  154,  133,    0,
        0,  201,  150,  231,    0,  163,  182,  205,    0,  176,
      148,  986,  214,  191,  662,    0,  986,  690,  687,  229,

      114,    0,  247,    0,  236,  240,  245,    0,  254,  257,
      273,    0,  262,  266,  271,    0,  685,  275,  282,    0,
      192,  279,  288,  280,  647,  298,  986,  300,  290,  680,
      302,  297,    0,  304,  308,  679,  312,  319,    0,  986,
      317,  319,  343,  310,  330,  335,  656,    0,  343,  370,
      374,    0,  382,  345,  986,  386,  388,  986,  391,  394,
      404,  406,  649,  404,  417,  423,  424,  391,  406,  634,
      636,  616,  629,  622,  639,  415,  326,    0,  422,  424,
      437,  429,  448,  439,  441,  450,  264,  639,  132,  459,
      447,  444,  193,  607,  598,  579,  986,  462,  452,  465,

      470,  474,  476,  581,  482,    0,  479,  495,  511,  329,
      537,  474,  481,  555,  524,  523,  487,  489,  517,  529,
      522,  499,  344,  518,  520,  516,  480,  480,  452,  426,
      505,  515,    0,  519,  549,  565,  557,  558,  573,  555,
      557,  425,  382,  396,  557,  381,  566,  586,  589,  528,
      607,  362,  574,  602,  578,  594,  610,  588,  630,  986,
      356,  622,  634,  618,  346,  600,  640,  611,  632,  335,
      229,  314,  658,  231,  661,  986,  214,  639,  184,  151,
      663,  635,  162,  664,  324,  122,   96,  649,  110,    0,
      676,  678,  986,  704,  714,  717,  727,  730,  733,   86,

      745,  757,  767,  777,  780,  783,  786,  796,  806,  809,
      812,  815,  818,  821,  824,  834,  837,  840,  850,  860,
      869,  879,  882,  892,  904,  913,  916,  926,  936,  943,
      953,  963,   53,  973
    } ;

static yyconst short int yy_def[335] =
    {   0,
      293,    1,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  293,  293,  293,  295,  296,  293,
      293,  293,  293,  293,   24,  293,  297,  297,  295,  298,
      293,  293,  293,  299,  296,  293,  300,   24,   25,  301,
      302,  293,  303,  293,  293,  293,  293,   42,  303,   49,
       49,   49,   28,  304,   28,   28,  298,  293,  293,  299,
       24,  293,  305,  301,  301,  302,  293,  293,  293,  293,
       49,  306,  293,  293,  293,  307,  308,   61,  293,   49,
       49,  309,  293,  304,  310,  293,  293,  293,  311,   28,
       28,  293,  293,  293,  293,  305,  293,  293,  306,  293,

      293,  307,  308,  312,  293,  293,  293,  313,  293,   61,
      309,  314,  293,  293,  293,  315,  310,  293,  293,  311,
       28,   28,  293,  293,  293,  316,  293,  293,  293,  312,
      293,  293,  313,  293,   61,  314,  293,  293,  315,  293,
      293,  293,  293,   48,  293,  293,  293,  317,  293,  293,
      293,  318,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  143,  319,  319,  319,  319,  167,  167,  167,
      144,  293,  293,  293,  317,  293,  293,  318,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  320,  167,  321,
      167,  167,  167,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  320,  322,  323,  293,  293,  293,  324,
      316,  167,  167,  293,  293,  325,  293,  293,  322,  326,
      323,  293,  293,  324,  167,  167,  293,  293,  325,  325,
      293,  293,  327,  293,  293,  293,  328,  293,  293,  293,
      167,  293,  293,  327,  293,  293,  328,  293,  293,  167,
      293,  293,  293,  293,  293,  293,  293,  167,  293,  293,
      293,  293,  293,  167,  293,  293,  293,  329,  329,  330,
      293,  330,  293,  293,  293,  293,  293,  293,  293,  331,
      332,  293,  293,  332,  293,  293,  293,  293,  293,  333,
      334,  334,    0,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293
    } ;

static yyconst short int yy_nxt[1031] =
    {   0,
       16,   16,   17,   16,   18,   19,   20,   16,   16,   16,
       16,   16,   21,   16,   22,   16,   23,   24,   25,   26,
       16,   16,   16,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   28,   16,   16,   29,   37,   30,   40,   32,   33,
       38,   39,   41,   31,   29,   31,   30,   37,   32,   33,
       38,   39,   42,   31,  291,   31,   43,   44,   32,   33,
       43,   43,   39,   43,   45,   43,   38,   38,   47,   78,
       78,   58,   47,   32,   32,   58,   53,   32,   33,   79,
       71,   79,   72,   94,   59,   94,   53,   63,   59,   73,

       53,   73,   46,   48,   74,   75,   91,   43,   44,   48,
       53,   49,   50,  290,   51,   98,   52,   49,   80,   53,
       81,   54,   52,   84,   98,   85,  129,   54,  129,   53,
       98,   90,   86,  288,   86,   93,   93,   87,   88,  293,
       98,  293,  293,   46,   48,   74,   75,  287,   43,   44,
      110,  110,   49,   50,  280,   51,  100,   52,   74,   74,
      189,  100,   54,   74,   75,  285,   55,   74,   75,  189,
      101,   78,   78,   53,  101,  122,   56,  103,  109,  104,
       87,   88,  109,   53,   46,   42,  105,  280,  105,   43,
       44,  106,  107,   43,   43,  143,   43,  118,   43,   87,

       87,   53,  121,  286,  111,  121,  112,  121,  124,  124,
       67,   53,   68,  113,   69,  113,   70,   53,  114,  115,
      118,  189,   87,   88,  213,   46,   71,   53,   72,  119,
      189,   93,   93,  119,   84,   73,   85,   73,  123,  273,
       74,   75,  123,   86,   82,   86,  128,  128,   87,   88,
      103,  278,  104,  106,  107,  131,  277,  106,  106,  105,
      131,  105,  106,  107,  106,  107,  134,  187,  134,  132,
      274,  135,  135,  132,  110,  110,  111,  188,  112,  114,
      115,  137,  144,  114,  114,  113,  137,  113,  114,  115,
      114,  115,  141,  141,  142,  138,  142,  124,  124,  138,

      145,  126,  145,  148,   53,  146,  146,  154,  154,  157,
      149,  157,  149,  171,   53,  150,  151,  128,  128,  156,
      156,  135,  135,  271,  153,  135,  135,  285,  153,  159,
      159,  160,  187,  160,  141,  141,  162,  162,  199,  172,
      199,  161,  188,  173,  271,  161,  163,  146,  146,  269,
       43,   44,  146,  146,   49,   80,  240,   81,  240,   52,
      150,  151,  154,  154,   54,  286,  164,  164,  164,  164,
      164,  165,  166,  167,  164,  168,  169,  170,  164,  164,
      164,  164,  164,  164,  164,  176,   46,  150,  150,  176,
      265,  150,  151,  255,  179,  255,  179,  261,  177,  180,

      180,  253,  177,  156,  156,  182,  182,  187,  159,  159,
      181,  184,  184,  252,  181,  183,  185,  188,  185,  183,
      187,  186,  186,  162,  162,  190,  187,  187,  189,  191,
      188,  193,  198,  198,  189,  251,  188,  188,  190,  180,
      180,  180,  180,  189,  190,  190,  182,  182,  230,  200,
      211,  200,  191,  191,  201,  201,  184,  184,  186,  186,
      202,  191,  202,  192,  206,  203,  203,  186,  186,  218,
      218,  207,  189,  207,  230,  189,  208,  209,  212,  198,
      198,  189,  201,  201,  189,  187,  217,  201,  201,  242,
      217,  203,  203,  203,  203,  188,  208,  209,  187,  231,

      225,  231,  189,  220,  232,  232,  218,  218,  188,  189,
      222,  189,  208,  208,  187,  226,  239,  239,  189,  243,
      187,  187,  232,  232,  188,  242,  222,  238,  208,  209,
      188,  188,  232,  232,  233,  223,  235,  236,  220,  223,
      211,  234,  148,  234,  189,  230,  235,  236,  189,  149,
      188,  149,  187,  189,  150,  151,  189,  189,  228,  241,
      187,  187,  188,  258,  245,  189,  235,  235,  187,  187,
      188,  188,  249,  249,  254,  254,  187,  187,  188,  188,
      245,  227,  235,  236,  204,  189,  188,  188,  250,  246,
      239,  239,  187,  246,  189,  263,  263,  248,  256,  216,

      256,  248,  188,  257,  257,  187,  249,  249,  259,  259,
      259,  257,  257,  187,  268,  188,  189,  267,  267,  254,
      254,  268,  264,  188,  188,  189,  262,  257,  257,  215,
      262,  259,  259,  259,  266,  269,  266,  187,  282,  267,
      267,  214,  204,  187,  197,  293,  189,  188,  283,  260,
      196,  263,  263,  188,  195,  189,  194,  267,  267,  275,
      275,  275,  275,  275,  275,  279,  282,  282,  279,  293,
      279,  189,  260,  273,  273,  289,  283,  283,  289,  282,
      289,  282,  164,  174,  158,  155,  273,  147,  273,  283,
      140,  283,  127,  126,  125,  293,   98,   98,   97,   65,

      276,   95,   92,  276,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   34,   34,   83,   83,
       77,   34,   77,   34,   65,   34,   35,   62,   35,   53,
       61,   53,   36,  293,   53,  293,   53,   53,   53,   57,
      293,   57,   60,  293,   60,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   66,  293,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   76,
       76,  293,  293,  293,   76,  293,   76,  293,   76,   89,
       89,  293,  293,  293,   89,  293,   89,  293,   89,   96,
      293,   96,   99,  293,   99,  102,  293,  102,  108,  108,

      293,  293,  293,  108,  293,  108,  293,  108,  116,  116,
      293,  293,  293,  116,  293,  116,  293,  116,  117,  293,
      117,  120,  293,  120,  130,  293,  130,  133,  293,  133,
      136,  293,  136,  139,  293,  139,  152,  152,  293,  293,
      293,  152,  293,  152,  293,  152,  175,  293,  175,  178,
      293,  178,  189,  293,  293,  293,  293,  293,  189,  189,
      189,  189,  205,  293,  293,  293,  293,  293,  293,  293,
      293,  205,  210,  293,  293,  293,  210,  293,  210,  293,
      210,  219,  293,  293,  293,  293,  293,  219,  219,  219,
      219,  221,  293,  221,  224,  293,  293,  293,  293,  293,

      224,  224,  293,  224,  229,  293,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  237,  293,  293,  293,
      237,  293,  237,  293,  237,  244,  293,  244,  247,  293,
      293,  293,  293,  293,  247,  247,  293,  247,  270,  293,
      293,  293,  293,  293,  270,  293,  293,  270,  272,  293,
      293,  293,  272,  293,  272,  281,  293,  293,  293,  293,
      293,  293,  293,  293,  281,  284,  293,  293,  293,  284,
      293,  284,  284,  293,  284,  292,  293,  293,  293,  292,
      293,  292,  292,  293,  292,   15,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static yyconst short int yy_chk[1031] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   18,   21,   18,   23,   31,   31,
       21,   21,   23,   18,   29,   18,   29,   22,   18,   18,
       22,   22,   24,   29,  333,   29,   24,   24,   29,   29,
       24,   24,   25,   24,   24,   24,   24,   24,   25,   45,
       45,   32,   25,   32,   32,   33,   53,   33,   33,   47,
       43,   47,   43,   59,   33,   59,   53,  300,   33,   43,

       56,   43,   24,   27,   43,   43,   56,   27,   27,   48,
       56,   27,   27,  289,   27,   68,   27,   48,   48,   55,
       48,   27,   48,   54,   68,   54,  101,   48,  101,   55,
       69,   55,   54,  287,   54,   58,   58,   54,   54,   61,
       69,   61,   61,   27,   28,   73,   73,  286,   28,   28,
       79,   79,   28,   28,  280,   28,   74,   28,   74,   74,
      189,   75,   28,   75,   75,  283,   28,   83,   83,  189,
       75,   78,   78,   91,   75,   91,   28,   77,   78,   77,
       86,   86,   78,   91,   28,   42,   77,  279,   77,   42,
       42,   77,   77,   42,   42,  121,   42,   87,   42,   87,

       87,   90,   90,  283,   82,   90,   82,   90,   94,   94,
       42,   90,   42,   82,   42,   82,   42,  121,   82,   82,
       88,  193,   88,   88,  193,   42,   49,  121,   49,   88,
      193,   93,   93,   88,   84,   49,   84,   49,   93,  271,
       49,   49,   93,   84,   49,   84,  100,  100,   84,   84,
      103,  277,  103,  105,  105,  106,  274,  106,  106,  103,
      107,  103,  107,  107,  103,  103,  109,  187,  109,  107,
      271,  109,  109,  107,  110,  110,  111,  187,  111,  113,
      113,  114,  122,  114,  114,  111,  115,  111,  115,  115,
      111,  111,  118,  118,  119,  115,  119,  124,  124,  115,

      123,  126,  123,  126,  122,  123,  123,  129,  129,  132,
      126,  132,  126,  144,  122,  126,  126,  128,  128,  131,
      131,  134,  134,  272,  128,  135,  135,  285,  128,  137,
      137,  138,  210,  138,  141,  141,  142,  142,  177,  144,
      177,  141,  210,  144,  270,  141,  143,  145,  145,  265,
      143,  143,  146,  146,  143,  143,  223,  143,  223,  143,
      149,  149,  154,  154,  143,  285,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  143,  150,  143,  150,  150,  151,
      261,  151,  151,  246,  153,  246,  153,  252,  151,  153,

      153,  244,  151,  156,  156,  157,  157,  164,  159,  159,
      156,  160,  160,  243,  156,  159,  161,  164,  161,  159,
      165,  161,  161,  162,  162,  164,  166,  167,  168,  168,
      165,  169,  176,  176,  169,  242,  166,  167,  165,  179,
      179,  180,  180,  169,  166,  167,  182,  182,  230,  181,
      191,  181,  167,  165,  181,  181,  184,  184,  185,  185,
      183,  167,  183,  166,  190,  183,  183,  186,  186,  199,
      199,  190,  192,  190,  229,  191,  190,  190,  192,  198,
      198,  192,  200,  200,  191,  205,  198,  201,  201,  228,
      198,  202,  202,  203,  203,  205,  207,  207,  208,  217,

      212,  217,  212,  205,  217,  217,  218,  218,  208,  213,
      208,  212,  208,  208,  209,  213,  222,  222,  213,  227,
      219,  224,  231,  231,  209,  226,  209,  221,  209,  209,
      219,  224,  232,  232,  220,  209,  234,  234,  219,  209,
      211,  220,  211,  220,  226,  216,  220,  220,  225,  211,
      211,  211,  235,  226,  211,  211,  250,  225,  215,  225,
      237,  238,  235,  250,  235,  250,  235,  235,  236,  247,
      237,  238,  240,  240,  245,  245,  239,  253,  236,  247,
      236,  214,  236,  236,  204,  241,  239,  253,  241,  236,
      239,  239,  249,  236,  241,  255,  255,  239,  248,  196,

      248,  239,  249,  248,  248,  254,  249,  249,  251,  251,
      251,  256,  256,  257,  268,  254,  258,  266,  266,  254,
      254,  264,  258,  257,  268,  258,  254,  257,  257,  195,
      254,  259,  259,  259,  262,  269,  262,  263,  282,  262,
      262,  194,  188,  267,  175,  269,  264,  263,  282,  251,
      174,  263,  263,  267,  173,  264,  172,  267,  267,  273,
      273,  273,  275,  275,  275,  278,  281,  284,  278,  171,
      278,  170,  259,  281,  284,  288,  281,  284,  288,  291,
      288,  292,  163,  147,  136,  130,  291,  125,  292,  291,
      117,  292,   99,   98,   95,   71,   70,   67,   65,   64,

      273,   62,   57,  275,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  295,  295,   51,   50,
       46,  295,   44,  295,   40,  295,  296,   36,  296,  297,
       35,  297,   20,   15,  297,    0,  297,  297,  297,  298,
        0,  298,  299,    0,  299,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  302,    0,  302,
      302,  302,  302,  302,  302,  302,  302,  302,  302,  303,
      303,    0,    0,    0,  303,    0,  303,    0,  303,  304,
      304,    0,    0,    0,  304,    0,  304,    0,  304,  305,
        0,  305,  306,    0,  306,  307,    0,  307,  308,  308,

        0,    0,    0,  308,    0,  308,    0,  308,  309,  309,
        0,    0,    0,  309,    0,  309,    0,  309,  310,    0,
      310,  311,    0,  311,  312,    0,  312,  313,    0,  313,
      314,    0,  314,  315,    0,  315,  316,  316,    0,    0,
        0,  316,    0,  316,    0,  316,  317,    0,  317,  318,
        0,  318,  319,    0,    0,    0,    0,    0,  319,  319,
      319,  319,  320,    0,    0,    0,    0,    0,    0,    0,
        0,  320,  321,    0,    0,    0,  321,    0,  321,    0,
      321,  322,    0,    0,    0,    0,    0,  322,  322,  322,
      322,  323,    0,  323,  324,    0,    0,    0,    0,    0,

      324,  324,    0,  324,  325,    0,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  326,    0,    0,    0,
      326,    0,  326,    0,  326,  327,    0,  327,  328,    0,
        0,    0,    0,    0,  328,  328,    0,  328,  329,    0,
        0,    0,    0,    0,  329,    0,    0,  329,  330,    0,
        0,    0,  330,    0,  330,  331,    0,    0,    0,    0,
        0,    0,    0,    0,  331,  332,    0,    0,    0,  332,
        0,  332,  332,    0,  332,  334,    0,    0,    0,  334,
        0,  334,  334,    0,  334,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1907031.l"
#define INITIAL 0
#line 2 "1907031.l"

// header files
#include<string.h>
#include<stdio.h>
#include<math.h>
#include<stdlib.h>

// keyword and datatype string collection
const char* keywords[] = {"vari","varf","varc","start","end","return","function","is","or","oris","si","loopf","loopw","ls","gr","eq","ge","le","ne","void",NULL};
const char* datatype[] = {"vari","varf","varc",NULL};

// check if a new variable name is a keyword
int is_keyword(const char* word) {
    for (int i = 0; keywords[i] != NULL; i++) {
        if (strcmp(keywords[i], word) == 0) {
            return 1;
        }
    }
    return 0;
}

// check if a new variable is a datatype
int is_datatype(const char* word) {
    for (int i = 0; datatype[i] != NULL; i++) {
        if (strcmp(datatype[i], word) == 0) {
            return 1;
        }
    }
    return 0;
}

// symbol table linked list that adds new values into head
struct Symbol_Table {
    char* name;
    char* datatype;
    char* value;
    struct Symbol_Table* next;
};

// head pointer for symbol table linked list
struct Symbol_Table* head = NULL;

// insert a new variable into symbol table
void insert_variable(const char* name, const char* datatype, const char* value) {
    struct Symbol_Table* new_symbol = malloc(sizeof(struct Symbol_Table));
    new_symbol->name = strdup(name);
    new_symbol->datatype = strdup(datatype);
    new_symbol->value = strdup(value);
    new_symbol->next = head;
    head = new_symbol;
}

// check if a variable is already declared
int is_declared(const char* name) {
    struct Symbol_Table* tmp = head;
    while (tmp != NULL) {
        if (strcmp(tmp->name, name) == 0) {
            return 1; // variable is already declared
        }
        tmp = tmp->next;
    }
    return 0; // variable is not declared
}

// update the value of a variable in the symbol table
int update_value(const char* name, const char* value) {
    struct Symbol_Table* tmp = head;
    while (tmp != NULL) {
        if (strcmp(tmp->name, name) == 0) {
            free(tmp->value); // free previous value
            tmp->value = strdup(value); // update new value
            return 1; 
        }
        tmp = tmp->next;
    }
    return 0; 
}

char s[1000];
int var_count=0, statement_count=0, function_count=0, header_count=0, temp_var_count=0, i=0;
int Unary_operator_count=0, Relational_operator_count=0, Assignment_operator_count=0, Logical_operator_count=0, Arithmatic_operator_count=0;
int mcmt_count=0, scmt_count=0;
int is_declared_check=0;
/* Labels for future need */
#define CONDITION 1

#define WHILE_BODY 2

#define WHILE_BEGIN 3

#define WHILE_END 4

#define IF_BODY 5

#define IF_CONDITION 6

#line 792 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 116 "1907031.l"


#line 946 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 294 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 986 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "1907031.l"
{ 
    scmt_count++;
    printf("single line comment\n"); 
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 122 "1907031.l"
{ 
    mcmt_count++;
    printf("multiple line comment\n");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 128 "1907031.l"
{
    char* token = strtok(yytext, " ,\t");
    char* type;
    int invalid = 0;
    temp_var_count=0; // Initialize the counter

    while (token != NULL) {
        if (!is_datatype(token)) {
            if (is_keyword(token)) {
                printf("ERROR: Reserved keyword can't be used as a variable name: %s\n", token);
                invalid = 1;
                break;
            }
            if (is_declared(token)) {
                printf("ERROR: Variable '%s' is already declared.\n", token);
                invalid = 1;
                break;
            } else {
                // Check for initialization
                char* init_value = strchr(token, '=');
                if (init_value != NULL) {
                    // Extract the initialization value
                    *init_value = '\0'; // Null-terminate the variable name
                    const char* varName = token;
                    if (is_declared(varName)) {
                        printf("ERROR: Variable '%s' is already declared.\n", token);
                        invalid = 1;
                        break;
                    }
                    Assignment_operator_count++;
                    printf("Assignment operator found\n");
                    init_value++; // Move to the value part
                    insert_variable(token, type, init_value);
                    printf("Variable name: %s, Datatype: %s, Initialized with: %s\n", token, type, init_value);
                } else {
                    insert_variable(token, type, "");
                    printf("Variable name: %s, Datatype: %s\n", token, type);
                }

                // Increment the counter for successfully declared variables
                temp_var_count++;
                var_count++;
            }
        } else {
            type = token;
        }
        token = strtok(NULL, " ,\t");
    }
    if (!invalid) {
        printf("Total variables declared: %d\n", temp_var_count);
    }
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 181 "1907031.l"
{
    char* var = strtok(yytext, " =");
    char* val = strtok(NULL, " =");
    if (!is_declared(var)) {
        printf("ERROR: Variable '%s' not declared before assignment.\n", var);
    }
    else {
        printf("ASSIGNMENT: Variable '%s' assigned value '%s'\n", var, val);
        update_value(var, val); // Update the variable value
    }
    
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 194 "1907031.l"
{statement_count++;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 197 "1907031.l"
{ 
    function_count++;
    printf("main function\n"); 
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 201 "1907031.l"
{
    function_count++;
    printf("function declaration\n");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 207 "1907031.l"
{ 
    header_count++;
    printf("header file\n");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 213 "1907031.l"
{
    Unary_operator_count++;
    printf("Unary operator found\n");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 217 "1907031.l"
{
    Unary_operator_count++;
    printf("Unary operator found\n");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 221 "1907031.l"
{
    Relational_operator_count++;
    printf("Relational operator found\n");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 225 "1907031.l"
{
    Assignment_operator_count++;
    printf("Assignment operator found\n");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 229 "1907031.l"
{
    Logical_operator_count++;
    printf("Logical operator found\n");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "1907031.l"
{
    Logical_operator_count++;
    printf("Logical operator found\n");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 237 "1907031.l"
{
    Arithmatic_operator_count++;
    printf("Arithmatic operator found\n");
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 241 "1907031.l"
{}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 243 "1907031.l"
ECHO;
	YY_BREAK
#line 1212 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CONDITION):
case YY_STATE_EOF(WHILE_BODY):
case YY_STATE_EOF(WHILE_BEGIN):
case YY_STATE_EOF(WHILE_END):
case YY_STATE_EOF(IF_BODY):
case YY_STATE_EOF(IF_CONDITION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 294 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 294 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 293);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 243 "1907031.l"


int yywrap()
{
	return 1;
}

int main()
{	
	yyin = fopen( "sample.c", "r" );
	yylex();
    printf("%d variables declared\n", var_count);
    printf("%d functions declared\n", function_count);
    printf("%d headers declared\n", header_count);
    printf("%d Unary operators\n", Unary_operator_count);
    printf("%d Relational operators\n", Relational_operator_count);
    printf("%d Assignment operators\n", Assignment_operator_count);
    printf("%d Logical operators\n", Logical_operator_count);
    printf("%d Arithmatic operators\n", Arithmatic_operator_count);
    printf("%d single line comments\n", scmt_count);
    printf("%d multiple line comments\n", mcmt_count);
	printf("%d statements\n", statement_count);
	return 0;
}