/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[301] =
    {   0,
        0,    0,   17,   15,   16,   15,   15,   15,   15,   15,
       15,   15,   15,   15,    4,   15,   15,    0,    0,    0,
        0,    0,   13,   13,   13,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       13,    0,    0,    9,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,   14,   14,    0,    0,    0,
        0,    0,    8,    0,    0,    0,   11,   11,   11,    0,
        0,   13,   13,    0,    0,    9,    2,    0,    0,    0,
        0,   14,    0,    0,    0,   12,   12,   12,    0,    0,

        0,    0,    0,   11,    0,    0,    0,   13,    0,    0,
       14,   14,    0,    0,    0,    0,   12,    0,    0,   11,
       11,    0,    0,    0,    0,   13,    0,    0,    0,   10,
       10,   10,    0,   14,   12,   12,    0,    0,   11,    0,
        3,    3,    3,    3,    3,    3,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   10,    0,   14,    0,
       12,    0,   11,    3,    3,    3,    3,    3,    0,    0,
        0,    3,    0,    3,    3,    0,    0,    0,    0,   10,
       10,    0,    0,   12,    3,    3,    0,    0,    0,    3,
        0,    0,    0,    3,    3,    3,    0,    3,    0,    0,

        0,   10,    0,    6,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    3,    3,    0,    0,    7,    0,   10,
        0,    0,    0,    0,    3,    3,    3,    3,    0,    0,
        0,    3,    3,    3,    3,    0,    0,    0,    0,    0,
        0,    0,    0,    3,    0,    0,    0,    3,    0,    3,
        0,    0,    3,    0,    0,    0,    3,    3,    3,    3,
        0,    3,    3,    0,    0,    3,    0,    5,    0,    0,
        0,    0,    3,    0,    3,    0,    3,    0,    0,    0,
        3,    3,    0,    0,    3,    0,    3,    0,    0,    0,
        3,    0,    0,    3,    0,    0,    0,    0,    0,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   20,   20,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       20,   20,   20,   27,   20,    1,   28,   25,   29,   30,

       31,   32,   33,   25,   34,   25,   25,   35,   36,   37,
       38,   25,   39,   40,   41,   25,   42,   43,   25,   25,
       25,   25,   44,   45,   20,   46,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    2,    3,    4,    2,    5,    2,    6,    7,    8,
        9,    6,   10,   11,   10,    2,    6,   12,   12,    2,
        2,    2,   13,    2,   14,   14,    6,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,    2,    7,    2
    } ;

static yyconst short int yy_base[344] =
    {   0,
        0,    0,  972, 1133, 1133,   43,   44,    0,  937,   36,
       46,   34,   77,   47, 1133,  119,  161,   52,  924,   64,
        0,   34,   56,   81,    0,  961,  928,    0,    0,    0,
        0,  869,  203,  102,  891,   69,  846,   88,  101,  245,
      875,  858,    0,   81,  134,   97,  105,  864,   92,  135,
        0,  138,  824,    0,    0,  798,  822,  791,   27,  110,
      788,  793,    0,  111,  142,  161,    0,  190,  164,  126,
        0,    0,  144,  213,    0,  148,  182,  226,    0,  195,
      209, 1133,  235,  153,  777,    0, 1133,  802,  796,  167,
      178,    0,  261,    0,  195,  253,  259,    0,  268,  203,

      789,  237,  189,    0,  266,  269,  280,  270,  736,  296,
     1133,  287,  273,  753,  298,  228,    0,  301,  303, 1133,
      305,  307,  333,  375,  309,  311,  717,    0,  314,  333,
      403,    0,  325,  316, 1133,  363,  335,  378,  367,  431,
      422,  471,  402,  316,   63,   45,  734,  116,  272,  467,
      367,  215,  699,  718,  405,  295,    0,  409,  412,  434,
      419,  432,  460,  476,  478,  482,  443,  675,  483,  477,
      706,  657,  496,  171,  262,  656,  485,  225,  639, 1133,
      500,  485,  505,  509,  128,  503,  533,  614,  635,  525,
      534,    0,  514,  574,  525,  598,  622,  454,   61,  544,

      542,  523,  560, 1133,  514,  561,  562,  590,  524,  551,
      614,  527,  558,  642,  511,  515,  492,  488,  540,  561,
      566,  645,    0,  598,  666,  588,  690,    0,  682,    0,
      603,  649,  612,  714,  690,  605,  619,  451,  419,  657,
      719,  629,  559,  738,  393,  634,  568,  762,  730,  653,
      710,  376,    0,  754,    0,  671,  717,  680,  786,  762,
      673,    0,  765,  701,  721,  738,  760, 1133,  757,  333,
      767,  584,  810,  792,  790,  802,  810,  630,  783,  827,
        0,  814,  816,  824,  828,  830,  832,  793,  256,  839,
      837,  222,  841,  843,  834,  246,    0,  860,  861, 1133,

      872,  855,  883,  866,  867,  183,  897,  910,  921,  932,
      871,  880,  915,  943,  916,  920,  926,  927,  954,  931,
      937,  965,  972,  983,  673,  994, 1005,  938, 1016, 1030,
     1041, 1052,  942, 1063,  948, 1074, 1085,  778,  949, 1096,
     1107,  167, 1118
    } ;

static yyconst short int yy_def[344] =
    {   0,
      300,    1,  300,  300,  300,  300,  301,  302,  300,  300,
      300,  300,  300,   13,  300,  303,  303,  300,  300,  301,
      304,  300,  300,  300,  305,  302,  300,  306,   13,   14,
      307,  308,  300,  309,  300,  300,  300,  300,   33,  309,
       40,   40,   40,   17,  310,   17,   17,  304,  300,  300,
      305,   13,  300,  311,  307,  308,  300,  300,  300,  300,
      300,   40,  312,  300,  300,  300,  313,  314,   52,  300,
       40,   40,  300,  310,  315,  300,  300,  300,  316,   17,
       17,  300,  300,  300,  300,  311,  300,  300,  312,  300,
      300,  313,  314,  317,  300,  300,  300,  318,  300,   52,

      315,  300,  300,  316,   17,   17,  300,  300,  300,  319,
      300,  300,  300,  317,  300,  300,  318,  300,   52,  300,
      300,  300,  300,  300,  300,  300,  300,  320,  300,  300,
      300,  321,  300,  300,  300,  300,  300,  300,  300,  300,
      322,  322,  142,  142,  142,  142,  323,  323,  323,  323,
      323,  323,  300,  320,  300,  300,  321,  300,  300,  300,
      300,  300,  300,  324,  324,  324,  166,  166,  300,  300,
      325,  142,  326,  142,  142,  323,  323,  323,  300,  300,
      300,  300,  300,  300,  166,  166,  300,  300,  325,  327,
      326,  328,  300,  300,  194,  329,  319,  142,  323,  330,

      300,  300,  300,  300,  300,  300,  327,  331,  328,  194,
      332,  300,  300,  329,  142,  323,  330,  330,  300,  300,
      300,  331,  333,  300,  300,  225,  334,  210,  332,  335,
      300,  210,  232,  336,  210,  300,  300,  300,  333,  225,
      337,  300,  300,  334,  335,  300,  300,  336,  300,  210,
      300,  338,  240,  337,  339,  300,  240,  257,  340,  240,
      300,  210,  210,  300,  300,  210,  300,  300,  341,  339,
      300,  300,  340,  300,  240,  300,  210,  300,  300,  341,
      240,  240,  300,  300,  240,  300,  210,  300,  300,  300,
      240,  300,  300,  240,  300,  300,  342,  343,  343,    0,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300
    } ;

static yyconst short int yy_nxt[1180] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,    4,    4,    4,
        4,    4,   10,    4,   11,    4,   12,   13,   14,    4,
       15,    4,    4,    4,   16,   16,    4,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   17,    4,    4,    4,   18,   20,   28,   21,
       31,   23,   24,   29,   30,   18,   22,   88,   22,   19,
       28,   23,   24,   29,   30,   30,   88,   20,   19,   21,
      170,   49,   38,   23,   23,  174,   22,   38,   22,   32,
       33,   23,   24,  172,   34,   35,   69,   69,   34,   34,
      175,   34,   36,   34,   29,   29,   49,  216,   23,   24,

       70,  172,   70,   34,   39,   62,   50,   63,   44,   83,
       83,   50,   40,   71,   64,   72,   64,   43,   44,   65,
       66,   37,   39,   45,   44,  170,   34,   35,   65,   66,
       40,   41,   44,   42,   44,   43,   80,   74,   81,   75,
       88,   45,   44,  100,  100,   34,   76,   84,   76,   84,
       88,   77,   78,  300,  177,  300,  300,   90,  185,   65,
       65,   65,   66,   37,   39,   77,   78,  185,   34,   35,
      108,  108,   40,   41,  197,   42,   90,   43,   65,   66,
      298,   69,   69,   45,  112,  112,   91,   34,   46,   99,
      113,   91,  113,   93,   99,   94,   54,  102,   47,   77,

       77,  122,   95,  122,   95,   37,   33,   96,   97,  172,
       34,   35,   96,   97,   34,   34,   74,   34,   75,   34,
      100,  100,   44,  105,  170,   76,  105,   76,  105,   34,
       77,   78,   44,   58,  170,   59,   44,   60,  106,   61,
      137,  102,  137,   77,   78,  177,   44,   37,   62,  297,
       63,  103,   83,   83,  121,  121,  103,   64,  199,   64,
      107,  295,   65,   66,   93,  107,   94,   45,  115,  123,
       96,   96,  124,   95,  115,   95,   96,   97,   96,   97,
      118,  170,  118,  292,  116,  119,  119,  108,  108,  116,
      134,  134,  125,   44,  125,  198,   44,  126,  126,  110,

      172,  128,  177,   44,  112,  112,   44,  182,  129,  182,
      129,  177,  133,  130,  131,  136,  136,  133,  119,  119,
      119,  119,  121,  121,  139,  139,  126,  126,  126,  126,
      138,  130,  131,  134,  134,  138,  140,  158,  281,  158,
       34,   35,  159,  159,   40,   71,  174,   72,  155,   43,
      130,  130,  161,  161,  172,   45,  174,  141,  141,   34,
      141,  141,  141,  142,  141,  143,  141,  144,  145,  146,
      141,  141,  141,  141,  141,  141,  170,   37,   39,  252,
      136,  136,   34,   35,  139,  139,   40,   71,  160,   72,
      162,   43,  162,  160,  178,  163,  163,   45,  262,  147,

      147,   34,  147,  147,  147,  148,  147,  149,  147,  150,
      151,  152,  147,  147,  147,  147,  147,  147,  155,   37,
      130,  131,  181,  181,  253,  169,  159,  159,  156,  159,
      159,  170,  174,  156,  140,  171,  161,  161,   34,   35,
      172,  174,   40,   71,  173,   72,  183,   43,  183,  163,
      163,  184,  184,   45,  252,  164,  164,   34,  164,  164,
      164,  165,  164,  166,  164,  167,  164,  168,  164,  164,
      164,  164,  164,  164,  169,   37,  170,  163,  163,  169,
      170,  169,  185,  186,  171,  169,  169,  187,  110,  171,
      215,  171,  172,  173,  170,  171,  171,  177,  173,  191,

      173,  192,  202,  202,  173,  173,  197,  177,  193,  174,
      193,  218,  186,  194,  195,  218,  186,  181,  181,  188,
      237,  186,  184,  184,  237,  201,  184,  184,  206,  228,
      201,  194,  195,  185,  203,  203,  203,  191,  171,  192,
      202,  202,  185,  195,  235,  235,  193,  208,  193,  172,
      213,  194,  195,  221,  219,  213,  219,  220,  220,  220,
      220,  203,  203,  203,  206,  206,  300,  218,  300,  300,
      236,  261,  236,  261,  171,  171,  204,  210,  220,  220,
      264,  211,  264,  208,  208,  211,  211,  171,  211,  212,
      211,  194,  194,  222,  238,  223,  283,  238,  283,  238,

      211,  210,  224,  204,  224,  211,  226,  225,  226,  211,
      211,  171,  211,  243,  211,  225,  226,  229,  243,  230,
      232,  233,  250,  250,  211,  197,  231,  128,  231,  251,
      233,  232,  233,  278,  129,  171,  129,  247,  189,  130,
      131,  205,  247,  279,  173,  210,  260,  260,  222,  211,
      223,  263,  263,  211,  211,  171,  211,  224,  211,  224,
      200,  188,  225,  226,  246,  170,  232,  232,  211,  240,
      250,  250,  300,  241,  300,  300,  190,  241,  241,  171,
      241,  242,  241,  225,  225,  229,  190,  230,  257,  258,
      275,  275,  241,  240,  231,  172,  231,  241,  258,  232,

      233,  241,  241,  171,  241,  272,  241,  235,  235,  189,
      272,  267,  267,  267,  185,  249,  241,  210,  277,  277,
      249,  211,  254,  180,  255,  211,  211,  171,  211,  179,
      211,  256,  271,  256,  257,  257,  257,  258,  266,  266,
      211,  240,  265,  170,  265,  241,  153,  266,  266,  241,
      241,  171,  241,  268,  241,  266,  266,  254,  135,  255,
      278,  267,  267,  267,  241,  210,  256,  187,  256,  211,
      279,  257,  258,  211,  211,  171,  211,  127,  211,  260,
      260,  269,  263,  263,  282,  282,  288,  274,  211,  240,
      276,  269,  274,  241,  120,  276,  288,  241,  241,  171,

      241,  111,  241,  268,  284,  110,  284,  275,  275,  285,
      285,  109,  241,  240,  286,  300,  286,  241,   88,  287,
      287,  241,  241,  171,  241,  289,  241,  277,  277,   88,
      278,  282,  282,  291,  291,  289,  241,  187,   87,  290,
      279,  285,  285,   57,  290,  285,  285,  287,  287,  287,
      287,  293,   85,  293,  291,  291,  294,  294,  294,  294,
      294,  294,  296,  278,  278,  296,   26,  296,   26,   82,
      187,  187,   73,  279,  279,   25,   25,   48,   51,   48,
       51,   25,   86,   25,   86,   25,   44,   73,   44,   44,
       68,   89,   44,   89,   44,   44,   44,   55,   55,   68,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   56,   56,   56,   57,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   67,   67,   92,  101,   92,  101,
       67,  104,   67,  104,   67,   79,   79,  114,  117,  114,
      117,   79,  154,   79,  154,   79,   98,   98,  157,  209,
      157,  209,   98,  239,   98,  239,   98,  132,  132,  245,
      270,  245,  270,  132,   53,  132,   52,  132,  172,   32,
       27,  300,  172,  300,  300,  172,  172,  172,  172,  176,
      300,  300,  300,  176,  300,  176,  185,  300,  300,  300,
      300,  300,  300,  185,  185,  185,  185,  196,  196,  300,

      300,  300,  300,  196,  300,  196,  300,  196,  207,  300,
      300,  300,  300,  300,  300,  207,  207,  207,  207,  214,
      300,  214,  300,  300,  300,  214,  214,  214,  300,  214,
      217,  217,  300,  217,  217,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  227,  227,  300,  300,  300,  300,
      227,  300,  227,  300,  227,  234,  234,  300,  300,  300,
      300,  234,  300,  234,  300,  234,  244,  300,  244,  300,
      300,  300,  244,  244,  244,  300,  244,  248,  300,  248,
      300,  300,  300,  248,  248,  248,  300,  248,  259,  259,
      300,  300,  300,  300,  259,  300,  259,  300,  259,  273,

      300,  273,  300,  300,  300,  273,  273,  273,  300,  273,
      280,  300,  300,  300,  300,  280,  300,  280,  280,  300,
      280,  299,  300,  300,  300,  300,  299,  300,  299,  299,
      300,  299,    3,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yyconst short int yy_chk[1180] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    6,    7,   10,    7,
       12,   22,   22,   10,   10,   18,    7,   59,    7,    6,
       11,    7,    7,   11,   11,   14,   59,   20,   18,   20,
      199,   23,   14,   23,   23,  146,   20,   14,   20,   12,
       13,   20,   20,  146,   13,   13,   36,   36,   13,   13,
      145,   13,   13,   13,   13,   13,   24,  199,   24,   24,

       38,  145,   38,   13,   39,   34,   24,   34,   44,   49,
       49,   24,   39,   39,   34,   39,   34,   39,   44,   34,
       34,   13,   16,   39,   46,  148,   16,   16,   64,   64,
       16,   16,   47,   16,   46,   16,   46,   45,   47,   45,
       60,   16,   47,   70,   70,   16,   45,   50,   45,   50,
       60,   45,   45,   52,  148,   52,   52,   65,  185,   65,
       65,   73,   73,   16,   17,   76,   76,  185,   17,   17,
       84,   84,   17,   17,  174,   17,   66,   17,   66,   66,
      342,   69,   69,   17,   90,   90,   66,   17,   17,   69,
       91,   66,   91,   68,   69,   68,  306,   77,   17,   77,

       77,  103,   68,  103,   68,   17,   33,   68,   68,  174,
       33,   33,   95,   95,   33,   33,   74,   33,   74,   33,
      100,  100,   80,   80,  152,   74,   80,   74,   80,   33,
       74,   74,   80,   33,  178,   33,   81,   33,   81,   33,
      116,   78,  116,   78,   78,  152,   81,   33,   40,  296,
       40,   78,   83,   83,  102,  102,   78,   40,  178,   40,
       83,  292,   40,   40,   93,   83,   93,   40,   96,  105,
       96,   96,  106,   93,   97,   93,   97,   97,   93,   93,
       99,  149,   99,  289,   97,   99,   99,  108,  108,   97,
      113,  113,  107,  105,  107,  175,  106,  107,  107,  110,

      175,  110,  149,  105,  112,  112,  106,  156,  110,  156,
      110,  149,  112,  110,  110,  115,  115,  112,  118,  118,
      119,  119,  121,  121,  122,  122,  125,  125,  126,  126,
      121,  129,  129,  134,  134,  121,  123,  133,  270,  133,
      123,  123,  133,  133,  123,  123,  144,  123,  130,  123,
      130,  130,  137,  137,  144,  123,  144,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  151,  123,  124,  252,
      136,  136,  124,  124,  139,  139,  124,  124,  136,  124,
      138,  124,  138,  136,  151,  138,  138,  124,  245,  124,

      124,  124,  124,  124,  124,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  124,  124,  131,  124,
      131,  131,  155,  155,  239,  141,  158,  158,  131,  159,
      159,  141,  143,  131,  140,  141,  161,  161,  140,  140,
      143,  143,  140,  140,  141,  140,  160,  140,  160,  162,
      162,  160,  160,  140,  238,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  142,  140,  150,  163,  163,  164,
      142,  165,  167,  167,  142,  166,  169,  170,  177,  164,
      198,  165,  198,  142,  177,  166,  169,  150,  164,  173,

      165,  173,  182,  182,  166,  169,  186,  150,  173,  142,
      173,  218,  166,  173,  173,  217,  165,  181,  181,  170,
      215,  166,  183,  183,  216,  181,  184,  184,  190,  209,
      181,  193,  193,  186,  187,  187,  187,  191,  190,  191,
      202,  202,  186,  195,  212,  212,  191,  190,  191,  215,
      195,  191,  191,  205,  201,  195,  201,  219,  219,  201,
      201,  203,  203,  203,  206,  207,  210,  200,  210,  210,
      213,  243,  213,  243,  206,  207,  187,  194,  220,  220,
      247,  194,  247,  206,  207,  194,  194,  194,  194,  194,
      194,  194,  194,  208,  221,  208,  272,  221,  272,  221,

      194,  196,  208,  203,  208,  196,  226,  208,  208,  196,
      196,  196,  196,  226,  196,  224,  224,  211,  226,  211,
      231,  231,  236,  236,  196,  197,  211,  197,  211,  237,
      233,  211,  211,  278,  197,  197,  197,  233,  189,  197,
      197,  188,  233,  278,  197,  214,  242,  242,  222,  214,
      222,  246,  246,  214,  214,  214,  214,  222,  214,  222,
      179,  237,  222,  222,  232,  176,  232,  232,  214,  225,
      250,  250,  240,  225,  240,  240,  325,  225,  225,  225,
      225,  225,  225,  225,  225,  229,  325,  229,  256,  256,
      261,  261,  225,  227,  229,  172,  229,  227,  258,  229,

      229,  227,  227,  227,  227,  258,  227,  235,  235,  171,
      258,  251,  251,  251,  168,  235,  227,  234,  264,  264,
      235,  234,  241,  154,  241,  234,  234,  234,  234,  153,
      234,  241,  257,  241,  257,  257,  241,  241,  265,  265,
      234,  244,  249,  147,  249,  244,  127,  249,  249,  244,
      244,  244,  244,  251,  244,  266,  266,  254,  114,  254,
      269,  267,  267,  267,  244,  248,  254,  269,  254,  248,
      269,  254,  254,  248,  248,  248,  248,  109,  248,  260,
      260,  338,  263,  263,  271,  271,  279,  260,  248,  259,
      263,  338,  260,  259,  101,  263,  288,  259,  259,  259,

      259,   89,  259,  267,  274,   88,  274,  275,  275,  274,
      274,   85,  259,  273,  276,   62,  276,  273,   61,  276,
      276,  273,  273,  273,  273,  279,  273,  277,  277,   58,
      280,  282,  282,  283,  283,  288,  273,  280,   57,  282,
      280,  284,  284,   56,  282,  285,  285,  286,  286,  287,
      287,  290,   53,  290,  291,  291,  290,  290,  293,  293,
      294,  294,  295,  298,  299,  295,  302,  295,  302,   48,
      298,  299,   42,  298,  299,  301,  301,  304,  305,  304,
      305,  301,  311,  301,  311,  301,  303,   41,  303,  303,
       37,  312,  303,  312,  303,  303,  303,  307,  307,   35,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  308,  308,  308,   32,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  309,  309,  313,  315,  313,  315,
      309,  316,  309,  316,  309,  310,  310,  317,  318,  317,
      318,  310,  320,  310,  320,  310,  314,  314,  321,  328,
      321,  328,  314,  333,  314,  333,  314,  319,  319,  335,
      339,  335,  339,  319,   27,  319,   26,  319,  322,   19,
        9,    3,  322,    0,    0,  322,  322,  322,  322,  323,
        0,    0,    0,  323,    0,  323,  324,    0,    0,    0,
        0,    0,    0,  324,  324,  324,  324,  326,  326,    0,

        0,    0,    0,  326,    0,  326,    0,  326,  327,    0,
        0,    0,    0,    0,    0,  327,  327,  327,  327,  329,
        0,  329,    0,    0,    0,  329,  329,  329,    0,  329,
      330,  330,    0,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  331,  331,    0,    0,    0,    0,
      331,    0,  331,    0,  331,  332,  332,    0,    0,    0,
        0,  332,    0,  332,    0,  332,  334,    0,  334,    0,
        0,    0,  334,  334,  334,    0,  334,  336,    0,  336,
        0,    0,    0,  336,  336,  336,    0,  336,  337,  337,
        0,    0,    0,    0,  337,    0,  337,    0,  337,  340,

        0,  340,    0,    0,    0,  340,  340,  340,    0,  340,
      341,    0,    0,    0,    0,  341,    0,  341,  341,    0,
      341,  343,    0,    0,    0,    0,  343,    0,  343,  343,
        0,  343,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1907031.l"
#define INITIAL 0
#line 2 "1907031.l"
#include<string.h>
#include<stdio.h>
#include<math.h>

char s[1000];
int var_count=0, statement_count=0, function_count=0, header_count=0, temp_var_count=0, i=0;
int Unary_operator_count=0, Relational_operator_count=0, Assignment_operator_count=0, Logical_operator_count=0, Arithmatic_operator_count=0;
int mcmt_count=0, scmt_count=0;
#line 738 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "1907031.l"


#line 892 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1133 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "1907031.l"
{ 
    scmt_count++;
    printf("single line comment\n"); 
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "1907031.l"
{ 
    mcmt_count++;
    printf("multiple line comment\n");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 45 "1907031.l"
{
	strcpy(s,yytext);
    temp_var_count=0;
	var_count++;
    temp_var_count++;
	for(i=0; i<strlen(s); i++){
		if(s[i]==',')
		{
			var_count++;
            temp_var_count++;
		}
        else if(s[i]=='=')
        {
            Assignment_operator_count++;
            printf("Assignment operator found\n");
        }
        else if(s[i]=='+' || s[i]=='-' || s[i]=='*' || s[i]=='/' || s[i]=='$' || s[i]=='^'){
            Arithmatic_operator_count++;
            printf("Arithmatic operator found\n");
        }
	}
    printf("%d variables declared\n", temp_var_count);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 70 "1907031.l"
{statement_count++;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "1907031.l"
{ 
    function_count++;
    printf("main function\n"); 
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "1907031.l"
{
    function_count++;
    printf("function declaration\n");
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "1907031.l"
{ 
    header_count++;
    printf("header file\n");
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "1907031.l"
{
    Unary_operator_count++;
    printf("Unary operator found\n");
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 93 "1907031.l"
{
    Unary_operator_count++;
    printf("Unary operator found\n");
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "1907031.l"
{
    Relational_operator_count++;
    printf("Relational operator found\n");
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "1907031.l"
{
    Assignment_operator_count++;
    printf("Assignment operator found\n");
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 105 "1907031.l"
{
    Logical_operator_count++;
    printf("Logical operator found\n");
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "1907031.l"
{
    Logical_operator_count++;
    printf("Logical operator found\n");
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 113 "1907031.l"
{
    Arithmatic_operator_count++;
    printf("Arithmatic operator found\n");
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "1907031.l"
{}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "1907031.l"
ECHO;
	YY_BREAK
#line 1113 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 119 "1907031.l"


int yywrap()
{
	return 1;
}

int main()
{	
	yyin = fopen( "sample.c", "r" );
	yylex();
    printf("%d variables declared\n", var_count);
    printf("%d functions declared\n", function_count);
    printf("%d headers declared\n", header_count);
    printf("%d Unary operators\n", Unary_operator_count);
    printf("%d Relational operators\n", Relational_operator_count);
    printf("%d Assignment operators\n", Assignment_operator_count);
    printf("%d Logical operators\n", Logical_operator_count);
    printf("%d Arithmatic operators\n", Arithmatic_operator_count);
    printf("%d single line comments\n", scmt_count);
    printf("%d multiple line comments\n", mcmt_count);
	printf("%d statements\n", statement_count);
	return 0;
}